# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.chat_id: '%env(TELEGRAM_CHAT_ID)%'
    app.job_feed_urls:
        - '%env(default::JOB_FEED_URL_1)%'
        - '%env(default::JOB_FEED_URL_2)%'
#        - '%env(default::JOB_FEED_URL_3)%'
#        - '%env(default::JOB_FEED_URL_4)%'
#        - '%env(default::JOB_FEED_URL_5)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Provider\JobProviderInterface:
            tags: ['app.job_provider']

    App\:
        resource: '../src/'
        exclude:
            - '../src/DependencyInjection/'
            - '../src/JobscanBundle.php'

    App\Command\RunPipelineCommand:
        arguments:
            $providers: !tagged_iterator app.job_provider

    App\Notification\TelegramNotifier:
        arguments:
            $botToken: '%telegram.bot_token%'
            $chatId: '%telegram.chat_id%'

    App\AI\Provider\OllamaClient:
        arguments:
            $apiBase: '%jobscan.llm.ollama.base_url%'
            $model: '%jobscan.llm.ollama.model%'

    App\AI\Provider\LMStudioClient:
        arguments:
            $apiBase: '%jobscan.llm.lmstudio.base_url%'
            $model: '%jobscan.llm.lmstudio.model%'

    App\AI\Provider\GeminiClient:
        arguments:
            $apiKey: '%jobscan.llm.gemini.api_key%'
            $model: '%jobscan.llm.gemini.model%'

    App\AI\Provider\LLMClientFactory:
        arguments:
            $providerName: '%jobscan.llm.provider%'

    llm.client:
        class: App\AI\Provider\LLMClientInterface
        factory: ['@App\AI\Provider\LLMClientFactory', 'create']

    App\AI\AIClient:
        arguments:
            $provider: '@llm.client'
            $cache: '@cache.app'
            $systemPrompt: '%app.ai_system_prompt%'
            $knownStack: '%app.known_stack%'

    App\Provider\RsFeedProvider:
        arguments:
            $feedUrls: '%app.job_feed_urls%'
        tags: ['app.job_provider']

    App\Provider\SearxProvider:
        arguments:
            $baseUrl: '%env(SEARXNG_URL)%'
            $searchQueries: '%app.searx_queries%'
            $locations: '%app.job_locations%'
        tags: [ 'app.job_provider' ]

    App\Processor\JobProcessor:
        arguments:
            $filterKeywords: '%app.filter_keywords%'
            $maxJobAgeDays: '%app.max_job_age_days%'

    App\Scoring\Scoring:
        arguments:
            $scoringConfig: '%app.scoring%'
