# yaml-language-server: $schema=../vendor/symfony/dependency-injection/Loader/schema/services.schema.json

parameters:
    telegram.bot_token: '%env(TELEGRAM_BOT_TOKEN)%'
    telegram.chat_id: '%env(TELEGRAM_CHAT_ID)%'
    ai.provider_name: '%env(AI_PROVIDER)%'
    ai.api_base: '%env(AI_API_BASE)%'
    ai.api_key: '%env(AI_API_KEY)%'
    ai.model: '%env(AI_MODEL)%'
    ai.gemini_api_key: '%env(GEMINI_API_KEY)%'
    ai.gemini_model: '%env(GEMINI_MODEL)%'
    app.job_feed_urls:
        - '%env(default::JOB_FEED_URL_1)%'
        - '%env(default::JOB_FEED_URL_2)%'
#        - '%env(default::JOB_FEED_URL_3)%'
#        - '%env(default::JOB_FEED_URL_4)%'
#        - '%env(default::JOB_FEED_URL_5)%'

services:
    _defaults:
        autowire: true
        autoconfigure: true

    _instanceof:
        App\Provider\JobProviderInterface:
            tags: ['app.job_provider']

    App\:
        resource: '../src/'

    App\Command\RunPipelineCommand:
        arguments:
            $providers: !tagged_iterator app.job_provider

    App\Notification\TelegramNotifier:
        arguments:
            $botToken: '%telegram.bot_token%'
            $chatId: '%telegram.chat_id%'

    App\AI\Provider\OpenAICompatibleProvider:
        arguments:
            $apiBase: '%ai.api_base%'
            $apiKey: '%ai.api_key%'
            $model: '%ai.model%'

    App\AI\Provider\GeminiProvider:
        arguments:
            $apiKey: '%ai.gemini_api_key%'
            $model: '%ai.gemini_model%'

    App\AI\Provider\AIProviderFactory:
        arguments:
            $providerName: '%ai.provider_name%'

    ai.provider:
        class: App\AI\Provider\AIProviderInterface
        factory: ['@App\AI\Provider\AIProviderFactory', 'create']

    App\AI\AIClient:
        arguments:
            $provider: '@ai.provider'
            $cache: '@cache.app'
            $systemPrompt: '%app.ai_system_prompt%'
            $knownStack: '%app.known_stack%'

    App\Provider\RsFeedProvider:
        arguments:
            $feedUrls: '%app.job_feed_urls%'
        tags: ['app.job_provider']

    App\Provider\SearxProvider:
        arguments:
            $baseUrl: '%env(SEARXNG_URL)%'
            $searchQueries: '%app.searx_queries%'
            $locations: '%app.job_locations%'
        tags: [ 'app.job_provider' ]

    App\Processor\JobProcessor:
        arguments:
            $filterKeywords: '%app.filter_keywords%'
            $maxJobAgeDays: '%app.max_job_age_days%'

    App\Scoring\Scoring:
        arguments:
            $scoringConfig: '%app.scoring%'
